[package]
name = "rust_opt_lib"
version = "0.1.0"
authors = ["shibh308 <s17097@tokyo.kosen-ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opimps = "0.1.4"